// Generated by gencpp from file envsim_msgs/Obstacle.msg
// DO NOT EDIT!


#ifndef ENVSIM_MSGS_MESSAGE_OBSTACLE_H
#define ENVSIM_MSGS_MESSAGE_OBSTACLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace envsim_msgs
{
template <class ContainerAllocator>
struct Obstacle_
{
  typedef Obstacle_<ContainerAllocator> Type;

  Obstacle_()
    : position()
    , scale(0.0)  {
    }
  Obstacle_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , scale(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _scale_type;
  _scale_type scale;





  typedef boost::shared_ptr< ::envsim_msgs::Obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::envsim_msgs::Obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacle_

typedef ::envsim_msgs::Obstacle_<std::allocator<void> > Obstacle;

typedef boost::shared_ptr< ::envsim_msgs::Obstacle > ObstaclePtr;
typedef boost::shared_ptr< ::envsim_msgs::Obstacle const> ObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::envsim_msgs::Obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::envsim_msgs::Obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::envsim_msgs::Obstacle_<ContainerAllocator1> & lhs, const ::envsim_msgs::Obstacle_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.scale == rhs.scale;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::envsim_msgs::Obstacle_<ContainerAllocator1> & lhs, const ::envsim_msgs::Obstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace envsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::envsim_msgs::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::envsim_msgs::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::envsim_msgs::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::envsim_msgs::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::envsim_msgs::Obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::envsim_msgs::Obstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::envsim_msgs::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08acace3eb15d64f642c494163931d7c";
  }

  static const char* value(const ::envsim_msgs::Obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08acace3eb15d64fULL;
  static const uint64_t static_value2 = 0x642c494163931d7cULL;
};

template<class ContainerAllocator>
struct DataType< ::envsim_msgs::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "envsim_msgs/Obstacle";
  }

  static const char* value(const ::envsim_msgs::Obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::envsim_msgs::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Position of obstacle\n"
"geometry_msgs/Vector3 position\n"
"\n"
"# Scale of obstacle\n"
"float64 scale\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::envsim_msgs::Obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::envsim_msgs::Obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.scale);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::envsim_msgs::Obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::envsim_msgs::Obstacle_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "scale: ";
    Printer<double>::stream(s, indent + "  ", v.scale);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENVSIM_MSGS_MESSAGE_OBSTACLE_H
