// Generated by gencpp from file dodgeros_msgs/Reference.msg
// DO NOT EDIT!


#ifndef DODGEROS_MSGS_MESSAGE_REFERENCE_H
#define DODGEROS_MSGS_MESSAGE_REFERENCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dodgeros_msgs/Setpoint.h>

namespace dodgeros_msgs
{
template <class ContainerAllocator>
struct Reference_
{
  typedef Reference_<ContainerAllocator> Type;

  Reference_()
    : header()
    , points()  {
    }
  Reference_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::dodgeros_msgs::Setpoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dodgeros_msgs::Setpoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::dodgeros_msgs::Reference_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dodgeros_msgs::Reference_<ContainerAllocator> const> ConstPtr;

}; // struct Reference_

typedef ::dodgeros_msgs::Reference_<std::allocator<void> > Reference;

typedef boost::shared_ptr< ::dodgeros_msgs::Reference > ReferencePtr;
typedef boost::shared_ptr< ::dodgeros_msgs::Reference const> ReferenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dodgeros_msgs::Reference_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dodgeros_msgs::Reference_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dodgeros_msgs::Reference_<ContainerAllocator1> & lhs, const ::dodgeros_msgs::Reference_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dodgeros_msgs::Reference_<ContainerAllocator1> & lhs, const ::dodgeros_msgs::Reference_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dodgeros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dodgeros_msgs::Reference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dodgeros_msgs::Reference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dodgeros_msgs::Reference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dodgeros_msgs::Reference_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dodgeros_msgs::Reference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dodgeros_msgs::Reference_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dodgeros_msgs::Reference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e374aa4139d56741a12f70c4fa22044e";
  }

  static const char* value(const ::dodgeros_msgs::Reference_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe374aa4139d56741ULL;
  static const uint64_t static_value2 = 0xa12f70c4fa22044eULL;
};

template<class ContainerAllocator>
struct DataType< ::dodgeros_msgs::Reference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dodgeros_msgs/Reference";
  }

  static const char* value(const ::dodgeros_msgs::Reference_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dodgeros_msgs::Reference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"dodgeros_msgs/Setpoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: dodgeros_msgs/Setpoint\n"
"# Angular rates in body frame\n"
"dodgeros_msgs/QuadState state\n"
"\n"
"# Single rotor thrusts\n"
"dodgeros_msgs/Command command\n"
"\n"
"================================================================================\n"
"MSG: dodgeros_msgs/QuadState\n"
"Header header\n"
"\n"
"# Time [s]\n"
"float64 t\n"
"\n"
"# Pose\n"
"geometry_msgs/Pose pose\n"
"\n"
"# Linear & angular velocity\n"
"geometry_msgs/Twist velocity\n"
"\n"
"# Linear & angular acceleration\n"
"geometry_msgs/Twist acceleration\n"
"\n"
"# Acc bias\n"
"geometry_msgs/Vector3 acc_bias\n"
"\n"
"# Gyro bias\n"
"geometry_msgs/Vector3 gyr_bias\n"
"\n"
"# Jerk\n"
"geometry_msgs/Vector3 jerk\n"
"\n"
"# Snap\n"
"geometry_msgs/Vector3 snap\n"
"\n"
"# Motor speeds\n"
"float64[] motors\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: dodgeros_msgs/Command\n"
"Header header \n"
"\n"
"# Time [s]\n"
"float64 t\n"
"\n"
"# If input is in terms of collective thrust & bodyrates or single rotor thrusts\n"
"bool is_single_rotor_thrust\n"
"\n"
"# Collective mass-normalized thrust [m/s^2]\n"
"float64 collective_thrust\n"
"\n"
"# Angular rates in body frame [rad/s]\n"
"geometry_msgs/Vector3 bodyrates\n"
"\n"
"# Single rotor thrusts [N]\n"
"float64[4] thrusts\n"
;
  }

  static const char* value(const ::dodgeros_msgs::Reference_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dodgeros_msgs::Reference_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Reference_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dodgeros_msgs::Reference_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dodgeros_msgs::Reference_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dodgeros_msgs::Setpoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DODGEROS_MSGS_MESSAGE_REFERENCE_H
