// Generated by gencpp from file dodgeros_msgs/Setpoint.msg
// DO NOT EDIT!


#ifndef DODGEROS_MSGS_MESSAGE_SETPOINT_H
#define DODGEROS_MSGS_MESSAGE_SETPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dodgeros_msgs/QuadState.h>
#include <dodgeros_msgs/Command.h>

namespace dodgeros_msgs
{
template <class ContainerAllocator>
struct Setpoint_
{
  typedef Setpoint_<ContainerAllocator> Type;

  Setpoint_()
    : state()
    , command()  {
    }
  Setpoint_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::dodgeros_msgs::QuadState_<ContainerAllocator>  _state_type;
  _state_type state;

   typedef  ::dodgeros_msgs::Command_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::dodgeros_msgs::Setpoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dodgeros_msgs::Setpoint_<ContainerAllocator> const> ConstPtr;

}; // struct Setpoint_

typedef ::dodgeros_msgs::Setpoint_<std::allocator<void> > Setpoint;

typedef boost::shared_ptr< ::dodgeros_msgs::Setpoint > SetpointPtr;
typedef boost::shared_ptr< ::dodgeros_msgs::Setpoint const> SetpointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dodgeros_msgs::Setpoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dodgeros_msgs::Setpoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dodgeros_msgs::Setpoint_<ContainerAllocator1> & lhs, const ::dodgeros_msgs::Setpoint_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dodgeros_msgs::Setpoint_<ContainerAllocator1> & lhs, const ::dodgeros_msgs::Setpoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dodgeros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dodgeros_msgs::Setpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dodgeros_msgs::Setpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dodgeros_msgs::Setpoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dodgeros_msgs::Setpoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dodgeros_msgs::Setpoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dodgeros_msgs::Setpoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dodgeros_msgs::Setpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7664ff7a9a9bd8a5486517df47844f44";
  }

  static const char* value(const ::dodgeros_msgs::Setpoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7664ff7a9a9bd8a5ULL;
  static const uint64_t static_value2 = 0x486517df47844f44ULL;
};

template<class ContainerAllocator>
struct DataType< ::dodgeros_msgs::Setpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dodgeros_msgs/Setpoint";
  }

  static const char* value(const ::dodgeros_msgs::Setpoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dodgeros_msgs::Setpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Angular rates in body frame\n"
"dodgeros_msgs/QuadState state\n"
"\n"
"# Single rotor thrusts\n"
"dodgeros_msgs/Command command\n"
"\n"
"================================================================================\n"
"MSG: dodgeros_msgs/QuadState\n"
"Header header\n"
"\n"
"# Time [s]\n"
"float64 t\n"
"\n"
"# Pose\n"
"geometry_msgs/Pose pose\n"
"\n"
"# Linear & angular velocity\n"
"geometry_msgs/Twist velocity\n"
"\n"
"# Linear & angular acceleration\n"
"geometry_msgs/Twist acceleration\n"
"\n"
"# Acc bias\n"
"geometry_msgs/Vector3 acc_bias\n"
"\n"
"# Gyro bias\n"
"geometry_msgs/Vector3 gyr_bias\n"
"\n"
"# Jerk\n"
"geometry_msgs/Vector3 jerk\n"
"\n"
"# Snap\n"
"geometry_msgs/Vector3 snap\n"
"\n"
"# Motor speeds\n"
"float64[] motors\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: dodgeros_msgs/Command\n"
"Header header \n"
"\n"
"# Time [s]\n"
"float64 t\n"
"\n"
"# If input is in terms of collective thrust & bodyrates or single rotor thrusts\n"
"bool is_single_rotor_thrust\n"
"\n"
"# Collective mass-normalized thrust [m/s^2]\n"
"float64 collective_thrust\n"
"\n"
"# Angular rates in body frame [rad/s]\n"
"geometry_msgs/Vector3 bodyrates\n"
"\n"
"# Single rotor thrusts [N]\n"
"float64[4] thrusts\n"
;
  }

  static const char* value(const ::dodgeros_msgs::Setpoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dodgeros_msgs::Setpoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Setpoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dodgeros_msgs::Setpoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dodgeros_msgs::Setpoint_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    s << std::endl;
    Printer< ::dodgeros_msgs::QuadState_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "command: ";
    s << std::endl;
    Printer< ::dodgeros_msgs::Command_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DODGEROS_MSGS_MESSAGE_SETPOINT_H
